# Generated by Django 6.0.6 on 2026-06-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninglead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Request'), ('CONTACTED', 'Quote Sent'), ('COMPLETED', 'Job Done')], default='NEW', max_length=10),
        ),
    ]
