# Generated by Django 6.0.6 on 2026-06-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_cleaninglead_final_quote_price_cleaninglead_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.DecimalField(decimal_places=2, default=95.0, max_digits=10)),
                ('sqft_multiplier', models.DecimalField(decimal_places=2, default=0.65, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Business Settings',
            },
        ),
        migrations.RemoveField(
            model_name='cleaninglead',
            name='system_estimated_price',
        ),
    ]
