# Generated by Django 6.0.6 on 2026-06-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_cleaninglead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninglead',
            name='system_estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cleaninglead',
            name='square_footage_estimate',
            field=models.IntegerField(help_text='Approximate sq. ft.'),
        ),
    ]
