# Generated by Django 6.0.6 on 2026-06-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_cleaninglead_system_estimated_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninglead',
            name='service_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential Home'), ('COMMERCIAL', 'Clinic/ Office/ Restaurant'), ('HOSPITALITY', 'Airbnb/ Cabin/ RV/ Motel'), ('CONSTRUCTION', 'Post Construction')], default='RESIDENTIAL', max_length=20),
        ),
    ]
