# Generated by Django 6.0.6 on 2026-07-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_cleaninglead_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
