# Generated by Django 6.0.6 on 2026-07-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_websitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='square_payment_link',
            field=models.URLField(blank=True, help_text='Your Square Canada Online Checkout link (e.g. https://square.link/u/...)', null=True),
        ),
    ]
