# Generated by Django 6.0.6 on 2026-07-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_businesssettings_square_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninglead',
            name='square_checkout_url',
            field=models.URLField(blank=True, help_text='Dynamic Square Canada payment link generated for this quote', max_length=500, null=True),
        ),
    ]
