# Generated by Django 6.0.6 on 2026-07-13 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20260712_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='cleaner_pin',
            field=models.CharField(default='1234', help_text='PIN for cleaners to log in and upload after photos', max_length=10),
        ),
        migrations.AlterField(
            model_name='cleaninglead',
            name='property_photo',
            field=models.URLField(blank=True, help_text='ImageKit URL for client property photo', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='PhotosLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(max_length=500)),
                ('photo_type', models.CharField(choices=[('BEFORE', 'Before Job'), ('AFTER', 'After Job')], default='BEFORE', max_length=10)),
                ('uploaded_by', models.CharField(choices=[('CLIENT', 'Customer'), ('CLEANER', 'Cleaner')], default='CLIENT', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bookings.cleaninglead')),
            ],
            options={
                'verbose_name_plural': 'Photos Log',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
