# Generated by Django 6.0.6 on 2026-07-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_businesssettings_cleaner_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninglead',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Specific focus areas or tasks requested by the customer', null=True),
        ),
    ]
