# Generated by Django 6.0.6 on 2026-07-17 01:34

from django.db import migrations, models

def populate_requested_end_time(apps, schema_editor):
    CleaningLead = apps.get_model('bookings', 'CleaningLead')
    from datetime import timedelta
    for lead in CleaningLead.objects.all():
        if lead.requested_date_time and not lead.requested_end_time:
            duration = lead.service_duration_hours or 4
            lead.requested_end_time = lead.requested_date_time + timedelta(hours=duration)
            lead.save()

def create_exclusion_constraint(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")
        schema_editor.execute(
            """
            ALTER TABLE bookings_cleaninglead
            ADD CONSTRAINT no_overlapping_bookings
            EXCLUDE USING gist (
                tstzrange(requested_date_time, requested_end_time) WITH &&
            )
            WHERE (status IN ('CONFIRMED', 'SCHEDULED', 'IN_PROGRESS'));
            """
        )

def remove_exclusion_constraint(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            "ALTER TABLE bookings_cleaninglead DROP CONSTRAINT IF EXISTS no_overlapping_bookings;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_cleaninglead_customer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninglead',
            name='requested_end_time',
            field=models.DateTimeField(blank=True, help_text='Calculated end time of the service.', null=True),
        ),
        migrations.AddField(
            model_name='cleaninglead',
            name='service_duration_hours',
            field=models.IntegerField(blank=True, help_text='Duration of service in hours. If blank, defaults to settings.', null=True),
        ),
        migrations.AlterField(
            model_name='cleaninglead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Request'), ('CONTACTED', 'Quote Sent'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Job Done'), ('CANCELLED', 'Cancelled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='NEW', max_length=15),
        ),
        migrations.RunPython(populate_requested_end_time, migrations.RunPython.noop),
        migrations.RunPython(create_exclusion_constraint, remove_exclusion_constraint),
    ]
