# Generated by Django 6.0.6 on 2026-07-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_cleaninglead_requested_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaninglead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Request'), ('CONTACTED', 'Quote Sent'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Job Done'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=15),
        ),
    ]
