# Generated by Django 6.0.6 on 2026-07-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_cleaninglead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaninglead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cleaninglead',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cleaninglead',
            name='requested_date_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cleaninglead',
            name='requested_end_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Calculated end time of the service.', null=True),
        ),
        migrations.AlterField(
            model_name='cleaninglead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Request'), ('CONTACTED', 'Quote Sent'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Job Done'), ('CANCELLED', 'Cancelled')], db_index=True, default='NEW', max_length=15),
        ),
    ]
