# Generated by Django 6.0.6 on 2026-07-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_alter_cleaninglead_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='google_review_link',
            field=models.URLField(blank=True, default='https://g.page/r/your-google-review-link', help_text='Your business Google Review page URL', null=True),
        ),
    ]
