# Generated by Django 6.0.6 on 2026-07-24 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_invoicesequence_businesssettings_tax_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(db_index=True, help_text='Unique phone number for login', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Cleaner email for job assignment notifications', max_length=254, null=True)),
                ('pin_hash', models.CharField(help_text='Hashed PIN string', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Employment active status')),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_LEAVE', 'On Leave'), ('SICK', 'Out Sick')], db_index=True, default='AVAILABLE', max_length=20)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cleaner Profile',
                'verbose_name_plural': 'Cleaner Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cleaninglead',
            name='assigned_cleaner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='bookings.cleanerprofile'),
        ),
    ]
